version: '3'
services: 
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    restart: always

  node:
    image: node:14
    build: .
    environment:
      - PORT=3003
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 3003:3003
    volumes:
      - .:/app/
      - /app/node_modules/
      - /app/deploy/
    depends_on:
      - postgres
    networks:
      - my-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5054:80"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: